[package]
name = "reversible_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rustyline = "9.0.0"

[dev-dependencies]
proptest = "1.5"
assert_cmd = "2.0"
predicates = "3.1"